version: '3.8'
services:
  nginx:
    container_name: app_nginx
    depends_on:
      - system
    image: nginx:alpine
    ports:
      - "8000:8000"
    networks:
      - production-network
    volumes:
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - system

  system:
    container_name: app_system
    user: ${COMPOSER_USER:-1000:1000}
    depends_on:
      - composer
      - db
    networks:
      - production-network
    build:
      context: .
      dockerfile: docker-compose/system/Dockerfile
    expose:
      - "9000"
    working_dir: /sistema
    volumes:
      - ./docker-compose/system/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./system:/sistema
      - /etc/localtime:/etc/localtime:ro
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM client_host=192.168.25.37
      - PHP_IDE_CONFIG=serverName=task-list

  composer:
    container_name: composer
    user: ${COMPOSER_USER:-1000:1000}
    image: composer
    working_dir: /sistema
    volumes:
      - ./system:/sistema
    command: composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --no-cache

  db:
    image: mysql:5.7
    container_name: container_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - production-network
    volumes:
      - mysql_dbdata:/var/lib/mysql

volumes:
  mysql_dbdata:

networks:
  production-network:
    driver:
      bridge